pqoqubbw/icons

icons/clock.tsx
icons/menu.tsx

This PR introduces two new icons: clock and menu.
https://github.com/user-attachments/assets/0d552812-eb31-497e-955f-d61ed622a18a
https://github.com/user-attachments/assets/cf44a443-4daa-40a9-8a23-71eb06d21381

feat: add clock and menu icons

---

icons/gauge.tsx

https://github.com/user-attachments/assets/000226ae-2957-4c3d-b3ba-062eb963eb22

feat: add gauge icon

---

icons/attach-icon.tsx
yarn.lock

[Screencast from 04-11-24 11:26:18 PM IST.webm](https://github.com/user-attachments/assets/f9edbcc4-c9da-4e6d-ad91-5cd08b828227)
added a new attach file icon

feat: Added attach icon

---

.vscode/extensions.json
icons/alarm-clock.tsx
icons/index.ts

[Screencast from 05-11-24 11:50:20 AM IST.webm](https://github.com/user-attachments/assets/096a4528-65d0-4074-bada-6e029d292a17)
added a new alarm clock icon which vibrates on hover

feat: Added alarm clock icon

---

icons/circle-check.tsx
icons/index.ts

Adding icon
Add animated circle-check
https://github.com/user-attachments/assets/181274f9-e520-4bd7-9667-6f9902d46a18
You can increase the animation time by 0.1 second if you like.

feat: add cicle check icon

---

icons/cart.tsx
icons/index.ts
icons/stethoscope.tsx

Feature (Icon) Addition
Added cart icon and stethoscope icon

icon:added-cart-stethoscope-icon

---

icons/index.ts
icons/logout.tsx

YES
Feature (Icon) Addition
https://github.com/user-attachments/assets/9717c91b-69af-4a6d-a52f-e525bf2ad42b

Added logout icon

---

icons/earth.tsx
icons/index.ts
icons/workflow.tsx

YES
feature
https://github.com/user-attachments/assets/8c46e39b-44f4-4d59-9388-8c7f0b9e0f66

Add new icons

---

icons/circle-help.tsx
icons/index.ts
icons/user.tsx

YES
Feature: 2 Icon added
https://github.com/user-attachments/assets/8c902662-9a29-45a7-b7b1-a88201cc46a7
https://github.com/user-attachments/assets/496b876d-3d57-4d20-93d1-fafb44b59829

Added circle-help and user icon

---

icons/index.ts
icons/shield-check.tsx

YES
feature
https://github.com/user-attachments/assets/87986daf-deaf-4f47-a056-122aab632c34

Add ShieldCheckIcon

---

icons/chart-bar-decreasing.tsx
icons/chart-bar-increasing.tsx
icons/chart-column-decreasing.tsx
icons/chart-column-increasing.tsx
icons/index.ts

YES
feature
https://github.com/user-attachments/assets/1caebb58-7537-4742-a081-7d569252e550

feat: add animated chart bar and column icons

---

icons/index.ts
icons/rocking-chair.tsx

YES
feature
https://github.com/user-attachments/assets/b6f50424-bd1f-4275-a47b-ec0cf8bb4a4b

Rocking chair icon

---

icons/index.ts
icons/loader-pinwheel.tsx

YES
feature
https://github.com/user-attachments/assets/5a97d18e-40c1-4d19-9839-a7544bdde5d1

feat: add LoaderPinwheelIcon

---

icons/id-card.tsx
icons/index.ts

YES
feature
https://github.com/user-attachments/assets/848eeb60-0cfc-49e9-a01a-bed076805d6c

feat: add IdCardIcon component and update icon list

---

icons/check-check.tsx
icons/check.tsx
icons/index.ts

YES
feature
check:
https://github.com/user-attachments/assets/026b28ff-c15a-4d1e-bffd-347ad82034f4
check-check:
https://github.com/user-attachments/assets/aad4a2db-e2af-442e-aaea-e75d92c3d213

feat: add check and check-check icons with animations

---

icons/chevrons-down-up.tsx
icons/chevrons-left-right.tsx
icons/chevrons-right-left.tsx
icons/chevrons-up-down.tsx
icons/circle-chevron-down.tsx
icons/circle-chevron-left.tsx
icons/circle-chevron-right.tsx
icons/circle-chevron-up.tsx
icons/index.ts

YES
feature
https://github.com/user-attachments/assets/fcd29160-0cd1-4bc7-b4ca-f1da28a69b28

Chevrons icons

---

icons/chrome.tsx
icons/figma.tsx
icons/fish-symbol.tsx
icons/git-commit-horizontal.tsx
icons/git-commit-vertical.tsx
icons/index.ts
icons/roller-coaster.tsx
icons/ship.tsx
icons/waypoints.tsx

YES
feature
https://github.com/user-attachments/assets/22a10417-836f-4972-9b43-938d15bb4881

New animated icons

---

icons/drum.tsx
icons/index.ts
icons/train-track.tsx
icons/webhook.tsx

YES
feature
https://github.com/user-attachments/assets/43572215-1b05-48bc-89f0-8a0ba3decc5b

feat: add DrumIcon component with animation effects

---

icons/airplane.tsx
icons/index.ts

y
feature
Please attach a short video demo of the changes.
https://github.com/user-attachments/assets/4cd018c8-c2e2-4275-8540-ad8c573a3c4b

airplane icon

---

README.md
icons/index.ts
icons/sparkles.tsx

YES
Adding the Sparkles icon to the library
https://github.com/user-attachments/assets/c29da7bc-db69-4b29-9a16-0d81af92e9c9

Added the sparkles icon

---

icons/activity.tsx
icons/index.ts

YES
Add icon
Add activity icon
https://github.com/user-attachments/assets/d0dd9104-a66a-46b5-8940-ba3b9457a971

feat: add activity icon

---

icons/ban.tsx
icons/index.ts

YES
Adding the Ban icon
https://github.com/user-attachments/assets/1134e22c-8adb-4da9-9567-ed05cf29c546

Added the Ban icon

---

icons/cog.tsx
icons/cpu.tsx
icons/index.ts
icons/rabbit.tsx

YES
feature
https://github.com/user-attachments/assets/ec9877be-b4cf-4954-8fa2-cbe0eb4f4418

feat: add CogIcon, CpuIcon, and RabbitIcon components with animations

---

icons/index.ts
icons/map-pin.tsx

YES
Added map-pin icon
https://github.com/user-attachments/assets/8f786c1c-57e8-4d4d-8d0e-53864e0df4a5

Added map-pin icon

---

icons/index.ts
icons/trending-up-down.tsx

YES
Adding the Trending Up Down icon
https://github.com/user-attachments/assets/9bc33da0-d828-478a-9c91-f072c185d027

Added trending-up-down icon

---

icons/clap.tsx
icons/index.ts

YES
Add icon
Add clap icon
https://github.com/user-attachments/assets/403c0f4b-9fc9-4174-b87f-5dd8cfd4998d
I tried to rotate the entire svg with an origin at x = 4px and y = 20px but it doesn't work. For some reason, the origin is not taken into account and the rotation is done from the center (because of the flex in the parent div??). So I tried to make a `motion.g` inside the svg with the path in it. It works, but when I rotate, my paths are hidden by the svg. I've seen that the `rocking-chair.tsx` icon has the same problem, the origin on the `motion.svg` is not taken into account. Can you help me fix this to get the animation without being hidden?
I show you a video if I put my animation on the motion.svg, the origin not taken into account. …

wip: clap icon

---

icons/drum.tsx

YES
refactor
no new behavior
remove redundant code about DrumIcon.
there is no animate about `opacity` and `duration` if fixed number, so remove the redundant code

refactor: remove redundant code about DrumIcon

---

icons/angry.tsx
icons/index.ts

YES
Add icon
Add angy icon
https://github.com/user-attachments/assets/f98cc7dd-cf5e-4ebd-9854-cb5f5a575652

feat: add angry icon

---

icons/index.ts
icons/wind.tsx

YES
Add icon
Add wind icon
https://github.com/user-attachments/assets/b9359258-ccc4-4b83-b78a-95ac05615f50

feat: add wind icon

---

icons/coffee.tsx
icons/index.ts

YES
Add icon
Add coffee icon
https://github.com/user-attachments/assets/c143e91c-df51-40cd-874d-9132293f94fa

feat: add coffee icon

---

icons/cctv.tsx
icons/index.ts

YES
Add icon
Add cctv icon
https://github.com/user-attachments/assets/9f2ee6b7-aac3-4c40-817f-5502aa20539f

feat: add cctv icon

---

icons/index.ts
icons/map-pin-check-inside.tsx
icons/map-pin-minus-inside.tsx
icons/map-pin-off.tsx
icons/map-pin-plus-inside.tsx

YES
Adding new map-pin-check-inside-icon
https://github.com/user-attachments/assets/6bbad618-937e-4ac5-bee5-7f1877cf860d

Adding new map-pin-check-inside icon

---

icons/index.ts
icons/map-pin-check.tsx
icons/map-pin-house.tsx
icons/map-pin-minus.tsx
icons/map-pin-plus.tsx
icons/map-pin-x-inside.tsx

YES
Added extra map-pin icons. Demo video will display the new icons
https://github.com/user-attachments/assets/df6dda7d-76e0-4d4f-a455-302c417c08bc

Extra map pin icons

---

icons/index.ts
icons/x.tsx

add X icon

---

icons/dribbble.tsx
icons/facebook.tsx
icons/index.ts
icons/instagram.tsx
icons/linkedin.tsx
icons/twitch.tsx
icons/youtube.tsx

YES
feat: ✨ add facebook icon
feat: ✨ add linkedin icon
feat: ✨ add youtube icon
feat: ✨ add instagram icon
feat: ✨ add twitch icon
feat: ✨ add dribbble icon
https://github.com/user-attachments/assets/3caa840f-1222-4065-b68f-73e2cfce771a

Add some social media icons

---

icons/cast.tsx
icons/index.ts
public/c/cast.json
scripts/registry-components.ts

YES
YES
add icon
add cast icon
https://github.com/user-attachments/assets/d1368fd4-225b-4357-a7e6-21a55d6e99f4

feat: add cast icon

---

icons/index.ts
icons/refresh-ccw-dot.tsx
icons/refresh-ccw.tsx
icons/refresh-cw-off.tsx
icons/refresh-cw.tsx
public/c/refresh-ccw-dot.json
public/c/refresh-ccw.json
public/c/refresh-cw-off.json
public/c/refresh-cw.json
scripts/registry-components.ts

YES
YES
Feature
https://github.com/user-attachments/assets/e075a7c4-d255-4d3e-b480-98c2e15362eb

Refresh icons

---

icons/index.ts
icons/panel-left-close.tsx
icons/panel-left-open.tsx
icons/panel-right-open.tsx
icons/user-round-plus.tsx
public/c/panel-left-close.json
public/c/panel-left-open.json
public/c/panel-right-open.json
public/c/user-round-plus.json
scripts/registry-components.ts

YES
YES
Add new icons: panel-right-open, panel-left-open, panel-left-close, user-round-plus
https://github.com/user-attachments/assets/0e8429bd-d1a1-4ddd-8c54-43a5b71e34a9

Add panel icons and user round plus icon
